/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.google.common.base.Joiner;

import java.util.Arrays;
import java.util.List;

public class HelloOtus {

    public static void main(String[] args) {

        List<String> dictionary = Arrays.asList("Apple", null, "Car", "Person", null, "Computer");

        String result = Joiner.on("; ")
                .skipNulls()
                .join(dictionary);

        System.out.println(result);

    }
}
